### PR TITLE
Update sites.json

### PR DESCRIPTION
**Pull request by sbritorodr**
Changed Spotify broken URL.

### CODE REVIEW

**Comment by tupaschoal** [comment]
This is a link to cancelling the subscription, but not to close the account, do you know if the latter is still possible? Otherwise we might want to change the difficulty

**Comment by tupaschoal** [comment]
Also, we keep the repo alive at https://github.com/jdm-contrib/jdm

**Comment by sbritorodr** [comment]
Sorry... Why the old repo is not supported anymore?

**Comment by tupaschoal** [comment]
We don't know, it looks like original owner transferred its ownership to someone that abandoned it, it's been years since they've merged a PR

**Comment by sbritorodr** [comment]
That's a shame... Those wasted stars... Is there anything we could do?
Like... Speaking to someone on GitHub to blank the repo or delete it?
Thanks for replying

**Comment by tupaschoal** [comment]
I don't think so, we did what we could which was forking, detaching the fork and keeping the project alive

**Comment by sbritorodr** [comment]
Okay, thanks for replying my mails and for keeping the project alive. This
git has helped me dozens of times

**Comment by tupaschoal** [comment]
My pleasure

**Pull request closed without merging**
