### PR TITLE
Add academia.edu

### PR DESCRIPTION
**Pull request by ArtificialTruth**

### CODE REVIEW

**Comment by tupaschoal** [comment]
Hello @ArtificialTruth ,

This repo is not being maintained anymore, but we are keeping it alive on a fork [here](https://github.com/jdm-contrib), would you kindly submit your PR there and close this one here? :)

**Comment by ArtificialTruth** [comment]
Hey @tupaschoal, can't you somehow automatically merge all the remaining ~104 pull requests?
Getting possibly 104 different users to submit them again to another repo may not work :/

**Comment by tupaschoal** [comment]
I thought about it @ArtificialTruth, but some of the PRs are quite old and I wouldn't know if the info was still accurate. Therefore, I monitor the new requests only.

**Comment by ArtificialTruth** [comment]
Hmm I see your point @tupaschoal. However I think you could say that about the entire database, since some of the data was made years ago. 
I think we should do it the other way around and push those, then people can make a new request if the data is inaccurate! 

Same goes for the current data, if some data is inaccurate they should make a pull request :)

**Pull request closed without merging**
