### PR TITLE
add th.json

### PR DESCRIPTION
**Pull request by wattachai**
add Thai translation

### CODE REVIEW

**Comment by wattachai** [comment]
Hello Robb,

I have come across `justdelete.me` recently and noticed that the project is looking for help on translation. I hope I could contribute to your project with my Thai skill.

Ps. I just start to use github. If I made any mistake, please feel free to point it out. I will try to fix it asap.

Enjoy coding!
Wattachai

**Comment by tupaschoal** [comment]
Hello @wattachai ,

This repo is not being maintained anymore, but we are trying to keep it alive on a detached fork [here](https://github.com/jdm-contrib), would you kindly submit your PR there and close this one here? :)

**Comment by wattachai** [comment]
Hello @tupaschoal,

Definitely yes! This would mean my contribution will be fruitful eventually. Let me create a new PR to the new repo. After that, I will close this one.

**Comment by tupaschoal** [comment]
Do submit your PR when you can @wattachai  :)

**Comment by wattachai** [comment]
@tupaschoal  PR sent. Closing this PR now. 😄

**Pull request closed without merging**
