### PR TITLE
Add Premiumize.me

### PR DESCRIPTION
**Pull request by CodeBrauer**
- [x] Have you updated to the latest version of the project? git pull
- [x] ~~If you have modified an existing service's difficulty, please explain why/give sources.~~
- [x] URLs must be direct links to either deletion, or if this is not available, a relevant help article.
- [x] Any steps for the process should be detailed in the notes (if necessary).
- [x] Be sure to indent 4 spaces per level.
- [x] Be sure to place your entry ALPHABETICALLY in the current list.
- [x] Please test that your changes work validating sites.json with something like JSON Lint

### CODE REVIEW

**Comment by CodeBrauer** [comment]
Any updates?

**Comment by CodeBrauer** [comment]
Any updates?

**Comment by CodeBrauer** [comment]
Any updates?

**Comment by tupaschoal** [comment]
Hello @CodeBrauer  ,

This repo is not being maintained anymore, but we are trying to keep it alive on a detached fork [here](https://github.com/jdm-contrib), would you kindly submit your PR there and close this one here? :)

**Comment by CodeBrauer** [comment]
Moved to https://github.com/jdm-contrib/justdelete.me/pull/186

**Pull request closed without merging**
